env: local

main-repo:
  name: cucumber-spring-demo.git
  url: git@github.com:pks9862728888/${main-repo.name}
  clone-branch: master
  clone-dir: .tmp/${main-repo.name}

logging:
  level:
    com.demo.automationtestdeveloper: DEBUG

command:
  mvn: mvn.cmd
